import "./globals.css";
import back from "../../public/back.jpg";
import Image from "next/image";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative bg-cover bg-center bg-no-repeat flex justify-center items-center min-h-screen">
        <div className="absolute inset-0">
          <Image
            src={back}
            alt="Background image"
            layout="fill"
            objectFit="cover"
            quality={100}
          />
        </div>
        <div className="relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}
